/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Banco.ContaCorrente;
import Banco.ContaPoupanca;
import Banco.ContaSalario;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel_g_gomes
 */
public class Gerencia extends javax.swing.JFrame {

    /**
     * Creates new form Gerencia
     */
    public Gerencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotaoTipoConta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoTextoNomeTitular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTextoCpfCnpj = new javax.swing.JTextField();
        botaoContaCorrente = new javax.swing.JRadioButton();
        botaoContaPoupanca = new javax.swing.JRadioButton();
        botaoContaSalario = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        CaixaSelecaoPFouPJ = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        botaoCriarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Gerente");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cliente");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome Titular");

        campoTextoNomeTitular.setBackground(new java.awt.Color(255, 255, 255));
        campoTextoNomeTitular.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF/CNPJ");

        campoTextoCpfCnpj.setBackground(new java.awt.Color(255, 255, 255));
        campoTextoCpfCnpj.setForeground(new java.awt.Color(0, 0, 0));

        grupoBotaoTipoConta.add(botaoContaCorrente);
        botaoContaCorrente.setForeground(new java.awt.Color(0, 0, 0));
        botaoContaCorrente.setText("Conta Corrente");
        botaoContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContaCorrenteActionPerformed(evt);
            }
        });

        grupoBotaoTipoConta.add(botaoContaPoupanca);
        botaoContaPoupanca.setForeground(new java.awt.Color(0, 0, 0));
        botaoContaPoupanca.setText("Conta Poupança");
        botaoContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContaPoupancaActionPerformed(evt);
            }
        });

        grupoBotaoTipoConta.add(botaoContaSalario);
        botaoContaSalario.setForeground(new java.awt.Color(0, 0, 0));
        botaoContaSalario.setText("Conta Salário");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de Conta");

        CaixaSelecaoPFouPJ.setBackground(new java.awt.Color(255, 255, 255));
        CaixaSelecaoPFouPJ.setForeground(new java.awt.Color(0, 0, 0));
        CaixaSelecaoPFouPJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Física", "Pessoa jurídica" }));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo de Titular");

        botaoCriarConta.setBackground(new java.awt.Color(204, 255, 255));
        botaoCriarConta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoCriarConta.setForeground(new java.awt.Color(0, 0, 0));
        botaoCriarConta.setText("CRIAR CONTA");
        botaoCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCriarContaMouseClicked(evt);
            }
        });
        botaoCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoContaCorrente)
                                .addGap(18, 18, 18)
                                .addComponent(botaoContaPoupanca)
                                .addGap(18, 18, 18)
                                .addComponent(botaoContaSalario)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTextoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CaixaSelecaoPFouPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(botaoCriarConta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaixaSelecaoPFouPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoContaCorrente)
                    .addComponent(botaoContaPoupanca)
                    .addComponent(botaoContaSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCriarConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContaCorrenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoContaCorrenteActionPerformed

    private void botaoContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContaPoupancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoContaPoupancaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
        new Cliente().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void botaoCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarContaActionPerformed
         
    }//GEN-LAST:event_botaoCriarContaActionPerformed

    private void botaoCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCriarContaMouseClicked
        String nome = this.campoTextoNomeTitular.getText();
        String cpfOuCnpj = this.campoTextoCpfCnpj.getText();
        String tipoPessoa = (String) this.CaixaSelecaoPFouPJ.getSelectedItem();
        
        Pessoa titular = null;
        if(tipoPessoa.equals("Pessoa Fisica")){
            titular = new PessoaFisica(nome, cpfOuCnpj);
        } else if(tipoPessoa.equals("Pessoa Jurídica")){
            titular = new PesoaJuridica(nome, cpfOuCnpj);
        }
        
        Conta conta = null;
        if(this.botaoContaCorrente.isSelected()){
            conta = new ContaCorrente(new Pessoa("Tico Tico no Fubá", "Carlinhos"));
        } else if(this.botaoContaPoupanca.isSelected()) {
            conta = new ContaPoupanca(new Pessoa("Tico Tico no Fubá", "Carlinhos"));
        } else if(this.botaoContaSalario.isSelected()) {
        conta = new ContaSalario(new Pessoa("Tico Tico no Fubá", "Carlinhos"));
        }
        
        meuBradesco.banco.add(conta);
        JOptionPane.showMessageDialog(this, "Sua conta foi criada com sucesso. o numero é: " + conta.getNumero);
        
        this.nomeTitular.setText("");
        this.cpfOuCnpj.setText("");
        
        for(Conta c : meuBradesco.banco){
            System.out.println("N°: " + c.getNumero() + " Titular: " + c.getTitular().getNome());
        }
    }//GEN-LAST:event_botaoCriarContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CaixaSelecaoPFouPJ;
    private javax.swing.JRadioButton botaoContaCorrente;
    private javax.swing.JRadioButton botaoContaPoupanca;
    private javax.swing.JRadioButton botaoContaSalario;
    private javax.swing.JButton botaoCriarConta;
    private javax.swing.JTextField campoTextoCpfCnpj;
    private javax.swing.JTextField campoTextoNomeTitular;
    private javax.swing.ButtonGroup grupoBotaoTipoConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
